language: node_js
node_js:
- '0.11'
sudo: false
install:
- npm install
- npm install -g gulp
script:
 - echo "SLACK_HOOK_URL=$KBC_SLACK_HOOK_URL" > ./config.env.production
 - gulp
 - gulp zip
 - gulp upload